version: '3.3'

services:
  app:
    command: npm run start:dev
    volumes:
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/node/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/node/zsh:delegated
