version: '3.3'

services:
  app:
    container_name: node-api
    image: pnaves/node-api:local
    build:
      context: .
      target: development
    depends_on:
      - postgres
      - mongo
    volumes:
      - .:/usr/app
    networks:
      - mongo
      - postgres

  postgres:
    container_name: node-api-postgres
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: ${POSTGRES_DATA_PATH}
    ports:
      - 5432:5432
    volumes:
      - /home/${USER}/.postgres/data:${POSTGRES_DATA_PATH}
    networks:
      - postgres

  mongo:
    container_name: node-api-mongo
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - /home/${USER}/.mongo/db:/data/db
    networks:
      - mongo

networks:
  mongo:
    name: mongo
    driver: bridge
  postgres:
    name: postgres
    driver: bridge
